server:
  port: 0
  
spring:
  application:
    name: manager-service
    
  datasource:
    url: jdbc:mysql://localhost:3306/project_management
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQLDialect

  data:
    mongodb:
      uri: mongodb://localhost:27017/projectDescStakeDatabase

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  mail:
    host: smtp.gmail.com
    port: 587
    username: menotify32@gmail.com
    password: wsepuiqkxnohpkai
    properties:
      mail:
        smtp: 
          auth: true
          starttks:
            enable: true
  boot:
    admin:
      client:
        url:
        - http://localhost:9001

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
 

management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
        