server:
  port: 8888
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/project
  datasource:
    url: jdbc:mysql://localhost:3306/project_management
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
      
  application:
    name: admin-view-service

logging:
  file:
    name: admin-view-service.log