server:
  port: 8505

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8777/eureka
   
     
spring:
  application:
    name: employee-service

  datasource:
    url: jdbc:h2:mem:testDB
    username: sa
    password: sa
    
  h2:
    console:
      enabled: true
      path: /h2
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  boot:
    admin:
      client:
        url:
        - http://localhost:8888
            
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'